name: hozmacore
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  intl: ^0.18.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  shared_preferences: ^2.1.1
  json_annotation: ^4.7.0

  #  firebase_core: ^1.2.0
  #  firebase_messaging: ^9.1.0
  retrofit: ^3.0.1+1
  logger: ^1.4.0
  dio: ^4.0.6
  badges: ^3.1.1
  provider: ^6.0.5
  # for mobile
  sqlite3_flutter_libs: ^0.5.15
  sqflite: ^2.0.3+1
  sqflite_common_ffi: ^2.1.1+1
  path: ^1.8.1
  #flutter_html_to_pdf: ^0.6.0

  open_file: ^3.3.2
  path_provider: ^2.0.15
  printing: ^5.11.0
  google_fonts: ^4.0.4

  responsive_framework: ^1.1.0

  flutter_barcode_scanner: ^2.0.0
  # connectivity: ^3.0.6
  connectivity_plus: ^4.0.2
  lottie: ^1.4.2
  get: ^4.6.5
  collection: ^1.17.1
  darq: ^2.0.0

  # ESC receipt printers libs
  flutter_pos_printer_platform: ^1.0.9
  desktop_multi_window: ^0.2.0
  window_manager: ^0.3.6
  desktop_lifecycle: ^0.1.0
  lazy_load_indexed_stack: ^1.0.1
  network_info_plus: ^3.0.5
  # esc_pos_utils: ^1.1.0

dev_dependencies:
  retrofit_generator: ^4.1.2
  build_runner: ^2.4.6
  json_serializable: ^6.5.4

#  floor_generator: ^1.1.0

#dependency_overrides:
#  floor_generator:

#  flutter_test:
#    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true

  #   To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/google_fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/google_fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/google_fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/google_fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/google_fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/google_fonts/Cairo-Bold.ttf
          weight: 700
